package com.bcinfo.umap.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-25T14:45:16.139+08:00
 * Generated source version: 3.5.3
 *
 */
@WebServiceClient(name = "MessageSenderService",
                  wsdlLocation = "file:/C:/Users/fengkunpeng/Desktop/migu/MessageSender.wsdl",
                  targetNamespace = "http://ws.umap.bcinfo.com")
public class MessageSenderService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.umap.bcinfo.com", "MessageSenderService");
    public final static QName MessageSender = new QName("http://ws.umap.bcinfo.com", "MessageSender");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/fengkunpeng/Desktop/migu/MessageSender.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessageSenderService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/fengkunpeng/Desktop/migu/MessageSender.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MessageSenderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessageSenderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageSenderService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MessageSenderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MessageSenderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MessageSenderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MessageSender
     */
    @WebEndpoint(name = "MessageSender")
    public MessageSender getMessageSender() {
        return super.getPort(MessageSender, MessageSender.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageSender
     */
    @WebEndpoint(name = "MessageSender")
    public MessageSender getMessageSender(WebServiceFeature... features) {
        return super.getPort(MessageSender, MessageSender.class, features);
    }

}
