package com.bcinfo.umap.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.3
 * 2022-07-25T14:45:16.134+08:00
 * Generated source version: 3.5.3
 *
 */
@WebService(targetNamespace = "http://ws.umap.bcinfo.com", name = "MessageSender")
@XmlSeeAlso({com.bcinfo.umap.ws.schemas.ObjectFactory.class, ObjectFactory.class})
public interface MessageSender {

    @WebMethod
    @RequestWrapper(localName = "sendSmMessage", targetNamespace = "http://ws.umap.bcinfo.com", className = "com.bcinfo.umap.ws.SendSmMessage")
    @ResponseWrapper(localName = "sendSmMessageResponse", targetNamespace = "http://ws.umap.bcinfo.com", className = "com.bcinfo.umap.ws.SendSmMessageResponse")
    @WebResult(name = "sendSmMessageReturn", targetNamespace = "http://ws.umap.bcinfo.com")
    public com.bcinfo.umap.ws.schemas.Response sendSmMessage(

        @WebParam(name = "header", targetNamespace = "http://ws.umap.bcinfo.com")
        com.bcinfo.umap.ws.schemas.RequestHeader header,
        @WebParam(name = "sourceAddr", targetNamespace = "http://ws.umap.bcinfo.com")
        String sourceAddr,
        @WebParam(name = "destMobiles", targetNamespace = "http://ws.umap.bcinfo.com")
        java.util.List<String> destMobiles,
        @WebParam(name = "content", targetNamespace = "http://ws.umap.bcinfo.com")
        String content
    );

    @WebMethod
    @RequestWrapper(localName = "sendSmTplMessage", targetNamespace = "http://ws.umap.bcinfo.com", className = "com.bcinfo.umap.ws.SendSmTplMessage")
    @ResponseWrapper(localName = "sendSmTplMessageResponse", targetNamespace = "http://ws.umap.bcinfo.com", className = "com.bcinfo.umap.ws.SendSmTplMessageResponse")
    @WebResult(name = "sendSmTplMessageReturn", targetNamespace = "http://ws.umap.bcinfo.com")
    public com.bcinfo.umap.ws.schemas.Response sendSmTplMessage(

        @WebParam(name = "header", targetNamespace = "http://ws.umap.bcinfo.com")
        com.bcinfo.umap.ws.schemas.RequestHeader header,
        @WebParam(name = "sourceAddr", targetNamespace = "http://ws.umap.bcinfo.com")
        String sourceAddr,
        @WebParam(name = "destMobiles", targetNamespace = "http://ws.umap.bcinfo.com")
        java.util.List<String> destMobiles,
        @WebParam(name = "templetId", targetNamespace = "http://ws.umap.bcinfo.com")
        String templetId,
        @WebParam(name = "tplVars", targetNamespace = "http://ws.umap.bcinfo.com")
        java.util.List<String> tplVars
    );
}
